### ISSUE TITLE
[Bug] 100% CPU - Download all artworks in library

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#133]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (4)

Download all artworks in library triggers 100% CPU (and 50% RAM) and makes music playback choppy in the meantime.

As soon as the process finishes the CPU drops back to normal.

This is also related to https://github.com/BLeeEZ/amperfy/issues/132 and seems to be the cause of it.

After the process is finished I have 155 albums and 905 songs incorrectly by Frank Sinatra and Quincy Jones.

[EDIT]

This bug https://github.com/BLeeEZ/amperfy/issues/128 seems to be back as well, showing 3 Not Checked Artworks.

![IMG_5896](https://user-images.githubusercontent.com/47334163/172917846-e3ead9cf-5e25-45c4-a02b-1801f24edf56.PNG)
![IMG_5897](https://user-images.githubusercontent.com/47334163/172917858-3d1c1124-2b91-41f2-ac44-9ec11a474009.PNG)
![IMG_5898](https://user-images.githubusercontent.com/47334163/172917861-1e143f8a-64e4-4801-a277-586b2f41ba5a.PNG)
![IMG_5899](https://user-images.githubusercontent.com/47334163/172918874-79b47bb2-b675-442e-912b-b98ca1ad58c5.PNG)

**Comment by bbsixzz** [comment]
Scrolling down the album list manually doesn't seem to exhibit this behavior.

**Comment by bbsixzz** [comment]
No problems in iSub.

![5175C9D1-C2FE-42C3-B875-92FE39CB8D24](https://user-images.githubusercontent.com/47334163/173013621-df345f85-cc46-43a1-a90c-51e286fe99b3.png)

**Comment by BLeeEZ** [comment]
https://github.com/BLeeEZ/amperfy/issues/133 has nothing to do with this. These are completely seperated functions and actions. The artwork download has no access to the songs.

**Comment by BLeeEZ** [comment]
I will reduce the number of parallel background artwork downloads. This should free enough CPU to allow an interrupt free playback.

**Comment by BLeeEZ** [comment]
If the "Not Checked Artworks" is > 0 a simple retrigger of "Download all artworks in library" should fix it. Or does the number stay > 0 even after retrigger?

**Comment by bbsixzz** [comment]
Reinstalled the app, retriggering doesn't fix it.

Btw the process of downloading seems to stop when the phone goes to sleep (background app refresh is on).

**Comment by BLeeEZ** [comment]
CPU load should be reduced with 8ae6a849532046257e1ff8076d833fe26e3fec87. "Not check artist" + "Cached artist" < "Artworks", this is correct. I will take a look at the naming and make it more self explanatory.

**Comment by bbsixzz** [comment]
This seems fixed in latest update 1.1.1 (1) although I had a hard crash to Springboard during caching with no crash report dialogue to send feedback. Caching resumed from where it left off once I started the app again.

**Comment by sandersantema** [comment]
> This seems fixed in latest update 1.1.1 (1) although I had a hard crash to Springboard during caching with no crash report dialogue to send feedback. Caching resumed from where it left off once I started the app again.

I've observed this hard crash to Springboard during downloading of songs as well, so I think it might be related to #143.
