### ISSUE TITLE
Album Artwork not loading when playing song from album

### ISSUE THREAD

**Issue by basdp** [BLeeEZ/amperfy#220]
See this video I made:
https://github.com/BLeeEZ/amperfy/assets/98805/2c022446-8c82-4dda-94e3-5eca15fa3439

As you see, Amperfy doesn't show album art in the 'now playing' view. both in as well as in Carplay. I can force the load by going into the '...' view. I think for some reason it doesn't download the artwork when you come from the Album view into the now playing view. 

I use Navidrome as a server.

Changing settings under Artwork doesn't make a difference (neither under download and display settings).

**Comment by BLeeEZ** [comment]
Yes this is a bug. I will take a look at it.

**Comment by BLeeEZ** [comment]
Bug is fixed in 3a468b141b47a945d066de5da536d6ddf24612d8

**Comment by basdp** [comment]
Should this fix be included in the latest version from the App Store? Because it looks like it still doesn't work in 1.1.5.

**Comment by BLeeEZ** [comment]
This fix will be available in the upcoming version 1.2.0.

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.2.0 (1). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
